spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true



key:
  access: JnqR7PGnOKXyikk3x974Utk15O9DH47rxLAbey1RNZU=
  refresh: hEdhi2CrR5/hGKlhM+EszdR69/Q8l7xlqb8zlKE5WPU=

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    group9:
      events: DEBUG