spring:
  application:
    name:Events
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com


key:
  access: JnqR7PGnOKXyikk3x974Utk15O9DH47rxLAbey1RNZU=
  refresh: hEdhi2CrR5/hGKlhM+EszdR69/Q8l7xlqb8zlKE5WPU=

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    group9:
      events: DEBUG



